version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app
    depends_on:
      - redis
    networks:
      - crawler-network
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - crawler-network
    restart: unless-stopped

networks:
  crawler-network:
    driver: bridge